# Generated by Django 4.2.17 on 2025-02-16 06:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='parent_asin',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='helpful_vote',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='review',
            name='images',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='text',
            field=models.TextField(default='some text here'),
        ),
        migrations.AddField(
            model_name='review',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AddField(
            model_name='review',
            name='title',
            field=models.CharField(default='Review Title', max_length=255),
        ),
    ]
